#!/usr/bin/env bash
# This script configures the Nginx server so that
# /redirect_me/ is redirecting to another page.

NEW_LOCATION="\n\tlocation /redirect_me/ {\n\t\treturn 301 https://google.com;\n\t}\n"
CONFIG_FILE="/etc/nginx/sites-available/default"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello, World!" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $NEW_LOCATION" "$CONFIG_FILE"

sudo service nginx restart
