#!/usr/bin/env bash
# This script configures an Nginx server to have a custom 404 page
# that contains the string "Ceci n'est pas une page".

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
NF_LOCATION="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $NF_LOCATION" /etc/nginx/sites-available/default
sudo service nginx reload
