#!/usr/bin/env bash
# Installs and configures HAproxy as a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo echo '
frontend front-backend
        bind 0:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 451721-web-01 54.144.142.186:80 check
        server 451721-web-02 100.27.14.169:80 check
' | sudo tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
