#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

hours=0
minutes=1

while [ $hours -lt 13 ]; do
    echo "Hour: $hours"
    minutes=1
    while [ $minutes -lt 60 ]; do
        echo "$minutes"
        ((minutes++))
    done
    ((hours++))
done
